# Generated by Django 5.1.2 on 2024-10-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idade',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
